# Copyright (c) 2021 Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
# Author: File autogenerated by brickshelper
# Purpose: The following file declares all the variables used by backend

variable "region" {
  description = "Target region where artifacts are going to be created"
}

variable "tenancy_ocid" {
  description = "OCID of tenancy"
}

variable "user_ocid" {
  description = "User OCID in tenancy. Currently hardcoded to user denny.alquinta@oracle.com"
}

variable "fingerprint" {
  description = "API Key Fingerprint for user_ocid derived from public API Key imported in OCI User config"
}

variable "private_key_path" {
  description = "Private Key Absolute path location where terraform is executed"
}
############## AUTENTICA_MVP COMPARTMENT VARIABLES ##############



variable "autentica_mvp_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "autentica_mvp_compartment_name" {
  description = "Compartment Display Name"
}

variable "autentica_mvp_compartment_description" {
  description = "Compartment Description"
}

variable "autentica_mvp_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "autentica_mvp_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "autentica_mvp_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## AUTENTICA_MVP COMPARTMENT VARIABLES ##############
############## HUB01 COMPARTMENT VARIABLES ##############



variable "hub01_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "hub01_compartment_name" {
  description = "Compartment Display Name"
}

variable "hub01_compartment_description" {
  description = "Compartment Description"
}

variable "hub01_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "hub01_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "hub01_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## HUB01 COMPARTMENT VARIABLES ##############
############## HUB01_ARTIFACTS COMPARTMENT VARIABLES ##############



variable "hub01_artifacts_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "hub01_artifacts_compartment_name" {
  description = "Compartment Display Name"
}

variable "hub01_artifacts_compartment_description" {
  description = "Compartment Description"
}

variable "hub01_artifacts_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "hub01_artifacts_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "hub01_artifacts_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## HUB01_ARTIFACTS COMPARTMENT VARIABLES ##############
############## HUB01_NETWORK COMPARTMENT VARIABLES ##############



variable "hub01_network_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "hub01_network_compartment_name" {
  description = "Compartment Display Name"
}

variable "hub01_network_compartment_description" {
  description = "Compartment Description"
}

variable "hub01_network_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "hub01_network_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "hub01_network_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## HUB01_NETWORK COMPARTMENT VARIABLES ##############
############## PRD01 COMPARTMENT VARIABLES ##############



variable "prd01_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "prd01_compartment_name" {
  description = "Compartment Display Name"
}

variable "prd01_compartment_description" {
  description = "Compartment Description"
}

variable "prd01_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "prd01_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "prd01_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## PRD01 COMPARTMENT VARIABLES ##############
############## PRD01_ARTIFACTS COMPARTMENT VARIABLES ##############



variable "prd01_artifacts_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "prd01_artifacts_compartment_name" {
  description = "Compartment Display Name"
}

variable "prd01_artifacts_compartment_description" {
  description = "Compartment Description"
}

variable "prd01_artifacts_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "prd01_artifacts_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "prd01_artifacts_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## PRD01_ARTIFACTS COMPARTMENT VARIABLES ##############
############## PRD01_NETWORK COMPARTMENT VARIABLES ##############



variable "prd01_network_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "prd01_network_compartment_name" {
  description = "Compartment Display Name"
}

variable "prd01_network_compartment_description" {
  description = "Compartment Description"
}

variable "prd01_network_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "prd01_network_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "prd01_network_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## PRD01_NETWORK COMPARTMENT VARIABLES ##############
############## STG01 COMPARTMENT VARIABLES ##############



variable "stg01_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "stg01_compartment_name" {
  description = "Compartment Display Name"
}

variable "stg01_compartment_description" {
  description = "Compartment Description"
}

variable "stg01_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "stg01_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "stg01_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## STG01 COMPARTMENT VARIABLES ##############
############## STG01_ARTIFACTS COMPARTMENT VARIABLES ##############



variable "stg01_artifacts_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "stg01_artifacts_compartment_name" {
  description = "Compartment Display Name"
}

variable "stg01_artifacts_compartment_description" {
  description = "Compartment Description"
}

variable "stg01_artifacts_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "stg01_artifacts_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "stg01_artifacts_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## STG01_ARTIFACTS COMPARTMENT VARIABLES ##############
############## STG01_NETWORK COMPARTMENT VARIABLES ##############



variable "stg01_network_parent_compartment_name" {
  description = "Display name of Parent Compartment"
  default     = ""
}

variable "stg01_network_compartment_name" {
  description = "Compartment Display Name"
}

variable "stg01_network_compartment_description" {
  description = "Compartment Description"
}

variable "stg01_network_is_root_child" {
  description = "Boolean that describes if the compartment is a child of root"
  default     = false
}

variable "stg01_network_enable_delete" {
  description = "Enables if Terraform is allowed to programatically delete this compartment upon invoking destroy command"
  default     = false
}

variable "stg01_network_sleep_timer" {
  description = "Sleep timer in seconds to wait for compartment to be created"
  default     = 60
}


############## STG01_NETWORK COMPARTMENT VARIABLES ##############
